export const reviewKeywords: readonly string[] = [
  'Affordable',
  'Amazing food',
  'Amazing service',
  'Beautiful location',
  'Best in town',
  'Best of the best',
  'Best restaurant in town',
  'Casual atmosphere',
  'Cheap drinks',
  'Delicious food',
  'Delicious',
  'Delightful',
  'Excellent food',
  'Excellent service',
  'Family friendly',
  'Fantastic food',
  'Friendly atmosphere',
  'Friendly staff',
  'Fun atmosphere',
  'Good drinks',
  'Good food',
  'Good for groups',
  'Good for kids',
  'Good service',
  'Great burgers',
  'Great for happy hour',
  'Great location',
  'Healthy options',
  'High quality',
  'Highly recommend',
  'Huge portions',
  'Huge selection',
  'Incredible food',
  'Incredible service',
  'Incredible',
  'Inexpensive',
  'Jam packed',
  'Just okay',
  'Just what I wanted',
  'Kid-friendly',
  'Large portions',
  'Large selection',
  'Lively atmosphere',
  'Must try',
  'My favorite',
  'My go-to',
  'Nachos were amazing',
  'Nice atmosphere',
  'Just okay',
  'Outstanding',
];

export const locations: readonly string[] = [
  'Albuquerque',
  'Anaheim',
  'Anchorage',
  'Arlington',
  'Atlanta',
  'Austin',
  'Aurora',
  'Albuquerque',
  'Bakersfield',
  'Baltimore',
  'Birmingham',
  'Birmingham',
  'Boston',
  'Bristol',
  'Buffalo',
  'Calgary',
  'Charlotte',
  'Chicago',
  'Chula Vista',
  'Cincinnati',
  'Cleveland',
  'Columbus',
  'Dallas',
  'Denver',
  'Detroit',
  'Edmonton',
  'Fontana',
  'Fort Worth',
  'Fremont',
  'Fresno',
  'Garden Grove',
  'Glasgow',
  'Glendale',
  'Greensboro',
  'Hartford',
  'Houston',
  'Huntington Beach',
  'Indianapolis',
  'Irvine',
  'Jacksonville',
  'Kansas City',
  'Las Vegas',
  'Leeds',
  'Liverpool',
  'London',
  'Long Beach',
  'Los Angeles',
  'Louisville',
  'Memphis',
  'Miami',
  'Milwaukee',
  'Minneapolis',
  'Modesto',
  'Montreal',
  'Moreno Valley',
  'Nashville',
  'New Orleans',
  'New York',
  'Newark',
  'Oakland',
  'Oceanside',
  'Oklahoma City',
  'Omaha',
  'Orlando',
  'Oxnard',
  'Philadelphia',
  'Phoenix',
  'Pittsburgh',
  'Portland',
  'Providence',
  'Raleigh',
  'Richmond',
  'Riverside',
  'Rochester',
  'Sacramento',
  'Seattle',
  'Salt Lake City',
  'San Bernardino',
  'San Diego',
  'San Francisco',
  'San Jose',
  'Santa Ana',
  'Santa Clarita',
  'Santa Rosa',
  'Seattle',
  'Sheffield',
  'St. Louis',
  'Stockton',
  'Tampa',
  'Toronto',
  'Tucson',
  'Vancouver',
  'Virginia Beach',
  'Washington DC',
  'Worcester',
];

export const cuisineAndKeywords: readonly { cuisine: string; keywords: string[] }[] = [
  {
    cuisine: 'American',
    keywords: [
      'Bakery',
      'BBQ',
      'Breakfast',
      'Brunch',
      'Burgers',
      'Cafe',
      'Chicken',
      'Dessert',
      'Pasta',
      'Pizza',
      'Salads',
      'Sandwiches',
      'Seafood',
      'Steak',
      'Wings',
    ],
  },
  {
    cuisine: 'Italian',
    keywords: [
      'Aglio e olio',
      'Bolognese',
      'Breadsticks',
      'Bruschetta',
      'Cacio e pepe',
      'Calzones',
      'Cannelloni',
      'Caprese',
      'Carbonara',
      'Gnocchi',
      'Lasagna',
      'Pasta',
      'Pizza',
      'Ravioli',
      'Salads',
      'Spaghetti',
    ],
  },
  {
    cuisine: 'Mexican',
    keywords: [
      'Burritos',
      'Chilaquiles',
      'Chiles',
      'Chimichangas',
      'Enchiladas',
      'Frijoles',
      'Guacamole',
      'Nachos',
      'Quesadillas',
      'Tacos',
      'Tamales',
      'Tlayudas',
      'Tortas',
      'Tortillas',
      'Tostadas',
    ],
  },
  {
    cuisine: 'Chinese',
    keywords: [
      'Beef and Broccoli',
      'Dumplings',
      'Egg Rolls',
      'Fried Rice',
      'Honey Walnut Shrimp',
      'Kung Pao Chicken',
      'Lo Mein',
      'Mongolian Beef',
      'Orange Beef',
      'Orange Chicken',
      'Sesame Chicken',
      'Shrimp Egg Foo Young',
      'Shrimp Fried Rice',
      'Shrimp Lo Mein',
      'Spring Rolls',
      'Sweet and Sour Chicken',
      'Sweet and Sour Pork',
      'Szechuan Chicken',
      "General Tso's Chicken",
    ],
  },
  {
    cuisine: 'Vietnamese',
    keywords: [
      'Banh Beo',
      'Banh Bot Loc',
      'Banh Canh',
      'Banh Cuon',
      'Banh Khot',
      'Banh Mi',
      'Banh Tom',
      'Banh Trang Nuong',
      'Banh Xeo',
      'Bun Bo Hue',
      'Bun Cha',
      'Bun Rieu',
      'Pho',
    ],
  },
  {
    cuisine: 'Japanese',
    keywords: [
      'Edamame',
      'Gyoza',
      'Miso Soup',
      'Mochi',
      'Okonomiyaki',
      'Onigiri',
      'Ramen',
      'Sashimi',
      'Soba',
      'Sukiyaki',
      'Sushi',
      'Tempura',
      'Teriyaki',
      'Udon',
      'Yakitori',
    ],
  },
  {
    cuisine: 'Indian',
    keywords: [
      'Aloo Gobi',
      'Biryani',
      'Butter Chicken',
      'Chaat',
      'Chana Masala',
      'Chicken Biryani',
      'Chicken Tikka Masala',
      'Curry',
      'Dal',
      'Kadai Paneer',
      'Korma',
      'Naan',
      'Pakora',
      'Samosa',
      'Tandoori',
      'Vindaloo',
    ],
  },
  {
    cuisine: 'Thai',
    keywords: [
      'Cashew Chicken',
      'Chicken Satay',
      'Green Curry',
      'Khao Mun Gai',
      'Khao Niew',
      'Khao Pad',
      'Khao Soi',
      'Pad Thai',
      'Papaya Salad',
      'Red Curry',
      'Tom Kha Gai',
      'Tom Yum',
    ],
  },
  {
    cuisine: 'Korean',
    keywords: [
      'Bibimbap',
      'Bulgogi',
      'Dakgalbi',
      'Ddeokbokki',
      'Doenjang Jjigae',
      'Gimbap',
      'Gochujang',
      'Japchae',
      'Jeyuk Bokkeum',
      'Jjajangmyeon',
      'Jjamppong',
      'Kimbap',
      'Kimchi Jjigae',
      'Kimchi Pancake',
      'Kimchi',
      'Korean Fried Chicken',
    ],
  },
  {
    cuisine: 'French',
    keywords: [
      'Baguettes',
      'Bouillabaisse',
      'Cassoulet',
      'Coq au vin',
      'Crepes',
      'Croissants',
      'Duck confit',
      'Escargot',
      'Foie gras',
      'French onion soup',
      'Galette des rois',
      'Macarons',
      'Quiche',
      'Ratatouille',
      `Creme brulee`,
      `Soupe a l'oignon`,
    ],
  },
  {
    cuisine: 'Greek',
    keywords: [
      'Baklava',
      'Feta',
      'Gyros',
      'Moussaka',
      'Souvlaki',
      'Spanakopita',
      'Tzatziki',
    ],
  },
];
